apiVersion: apps/v1
kind: Deployment
metadata:
  name: knuto-operator-secrets
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      knuto: secrets
  template:
    metadata:
      labels:
        knuto: secrets
        app: knuto
    spec:
      serviceAccountName: knuto-secrets
      containers:
      - name: knuto-secrets
        image: {{ .Values.image }}
        command:
        - knuto-secrets
        - -v
        {{- range .Values.kafkauser_source_namespaces }}
        - --kafka-user-topic-source-namespace
        - {{ . }}
        {{- end }}
        {{- range $secret_type, $server := .Values.secret_type_to_bootstrap_server }}
        - --secret-type-to-bootstrap-server
        - {{ $secret_type }}={{ $server }}
        {{- end }}
        - {{ .Values.strimzi_namespace }}
{{ range $idx, $namespace := .Values.kafkauser_source_namespaces }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knuto-operator-kafkaentities-{{ . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      knuto: kafkaentities-{{ . }}
  template:
    metadata:
      labels:
        knuto: kafkaentities-{{ . }}
        app: knuto
    spec:
      serviceAccountName: knuto-kafka-users-topics
      containers:
      - name: knuto-kafkaentities
        image: {{ $.Values.image }}
        command:
        - knuto-kafkauser
        - -v
        - --kafka-user-topic-destination-namespace
        - {{ $.Values.strimzi_namespace }}
        - {{ $namespace }}
{{ end }}

